[workspace]
members = [
    "lexer",
    "parser",
    "ast",
    "llvm",
    "x86",
    "frontend",
    "backend",
    "driver",
    "assembler",
    "linker",
    "typechecker",
    "common"]
resolver = "3"
