[package]
name = "driver"
version = "0.1.0"
edition = "2024"

[dependencies]
backend = { path = "../backend" }
frontend = { path = "../frontend" }
ast      = { path = "../ast" }

[[bin]]
name = "dclang"
path = "src/main.rs"
